import { MongoClient } from 'mongodb';

async function seedBlogs() {
  const uri = process.env.MONGODB_URI;
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const db = client.db('my-portfolio-cluster'); // your DB name
    const blogsCollection = db.collection('blogs');

    // Example blogs generated by ChatGPT
    const sampleBlogs = [
      {
        title: "Introduction to React.js",
        summary: "Learn the basics of React.js, a popular JavaScript library for building user interfaces.",
        content: "Full blog content here...",
        createdAt: new Date(),
      },
      {
        title: "Getting Started with MongoDB Atlas",
        summary: "A beginner's guide to using MongoDB Atlas cloud database service.",
        content: "Full blog content here...",
        createdAt: new Date(),
      },
      // Add 8 more similar objects here...
    ];

    const result = await blogsCollection.insertMany(sampleBlogs);
    console.log(`Inserted ${result.insertedCount} blogs.`);
  } finally {
    await client.close();
  }
}

seedBlogs().catch(console.error);
